import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import TitleCarousel from "@/components/app_component/common/TitleCarousel";
import { UserProvider } from "./context/UserContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SMTPMaster",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", 
  }
};

// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning  
      >
        <TitleCarousel />
        <UserProvider>
          {children}
        </UserProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}